Sprint_3
vazheninaMargo/Sprint_3 pull request #1
Opened 2022-05-25 17:25 UTC by vazheninaMargo

Unit-тесты:
Добавлены тесты для ручки создания курьера.
Добавлены тесты для ручки логина курьера.
Добавлены параметризованные тесты для ручки создания заказа.
Добавлены тесты для ручки получения списка заказов.

2022-05-26 08:03 UTC, nrasskosova requested changes

2022-05-26 08:03 UTC, nrasskosova commented on src/test/java/Courier/CourierTestHelper.java
> +    static public void printResponseBodyToConsole(Response response) {
так - можно.
Но если тестов будет много, то для каждого писать вывод консоль - утомительно. 
RestAssured позволяет настроить вывод в консоль и прикрепление ответов-запросов к allure-отчету с помощью фильтров.

2022-05-26 14:53 UTC, vazheninaMargo commented on src/test/java/Courier/CourierCreateTest.java
> +    @DisplayName("Check creating of courier with empty firstName")
В документации к API не указано, что этот параметр является необязательным. Получается что баг либо в документации, либо в API
https://qa-scooter.praktikum-services.ru/docs/
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/103767996/170513730-51ef42fa-6c4c-4776-b942-dbc4b6fb836b.png">

Пример необязательного параметра можно посмотреть в запросе **Orders - Получение списка заказов.**
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/103767996/170513842-61f61c01-b429-482d-8d09-0545943c7bfe.png">

2022-05-26 14:53 UTC, vazheninaMargo commented on src/test/java/Courier/CourierCreateTest.java
> +    public void checkCreatingOfCourierWithoutFirstName() {
Тоже самое, что и у предыдущего замечания

2022-05-27 06:20 UTC, nrasskosova commented on src/test/java/Courier/CourierCreateTest.java
> +    @DisplayName("Check creating of courier with empty firstName")
да, в документации явно не написано, какие поля обязательные. Но есть вот эта часть документации, которая говорит о том, что 

> Запрос без логина или пароля:
> HTTP/1.1 400 Bad Request
> {
>   "message": "Недостаточно данных для создания учетной записи"
> }
>

2022-05-27 06:32 UTC, nrasskosova commented on src/test/java/Courier/CourierCreateTest.java
> +        LoginCourierModel loginCourierModel = new LoginCourierModel(
лишний объект, нигде не используется

2022-06-11 13:07 UTC, merged